language: php
sudo: false

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mysql -e 'create database test;'
  - php app/console doctrine:schema:create

script:
